### PR TITLE
update config.{guess,sub} scripts

### PR DESCRIPTION
**Pull request by moodyhunter**
The last time `config.{guess,sub}` files have been updated was "2013-11-29", which does not have many new features, e.g. support for the RISC-V architecture, this PR updates these files to a recent version.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Done.

**Comment by moodyhunter** [comment]
Hi, I see you have updated those files to `timestamp='2016-10-02'`, is there a particular reason for not updating it to the latest version?

**Comment by michaelrsweet** [comment]
@moodyhunter It is the version I've tested with my various projects. Since I *just* did that update in most of my other projects in the last couple months I'm not keen on messing with this again unless there is a specific reason. Does the 2016-10-02 file not support RISC-V? The latest automake doesn't build/install on macOS (for example) so I'm not keen on pulling in something that won't work everywhere.

**Comment by moodyhunter** [comment]
Okay, I get your point.

Yes, `2016-10-02` works completely fine. Thanks :)

**Pull request closed without merging**
